# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/Z01R/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/Z01R/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/asus/Z01R/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/asus/Z01R/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/asus/Z01R/proprietary/etc/bluetooth/bt_profile.conf:system/etc/bluetooth/bt_profile.conf \
    vendor/asus/Z01R/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/asus/Z01R/proprietary/etc/bluetooth/bt_stack_userdebug.conf:system/etc/bluetooth/bt_stack_userdebug.conf \
    vendor/asus/Z01R/proprietary/etc/bluetooth/interop_database.conf:system/etc/bluetooth/interop_database.conf \
    vendor/asus/Z01R/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/asus/Z01R/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/asus/Z01R/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/asus/Z01R/proprietary/etc/nqnfcee_access.xml:system/etc/nqnfcee_access.xml \
    vendor/asus/Z01R/proprietary/etc/nqnfcse_access.xml:system/etc/nqnfcse_access.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/LteDirectDiscovery.xml:system/etc/permissions/LteDirectDiscovery.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/RemoteSimlock.xml:system/etc/permissions/RemoteSimlock.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/asus.hardware.touchgesture.double_tap.xml:system/etc/permissions/asus.hardware.touchgesture.double_tap.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/asus.hardware.touchgesture.launch_app.xml:system/etc/permissions/asus.hardware.touchgesture.launch_app.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/asus.hardware.touchgesture.swipe_up.xml:system/etc/permissions/asus.hardware.touchgesture.swipe_up.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/com.nxp.nfc.nq.xml:system/etc/permissions/com.nxp.nfc.nq.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/lpa.xml:system/etc/permissions/lpa.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/asus/Z01R/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/asus/Z01R/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/asus/Z01R/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/asus/Z01R/proprietary/etc/wfdconfig_720.xml:system/etc/wfdconfig_720.xml \
    vendor/asus/Z01R/proprietary/etc/wfdconfig_MI.xml:system/etc/wfdconfig_MI.xml \
    vendor/asus/Z01R/proprietary/etc/wfdconfig_aac-off.xml:system/etc/wfdconfig_aac-off.xml \
    vendor/asus/Z01R/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/asus/Z01R/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    vendor/asus/Z01R/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/asus/Z01R/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/asus/Z01R/proprietary/framework/com.nxp.nfc.nq.jar:system/framework/com.nxp.nfc.nq.jar \
    vendor/asus/Z01R/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/asus/Z01R/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/asus/Z01R/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/asus/Z01R/proprietary/framework/oem-services.jar:system/framework/oem-services.jar \
    vendor/asus/Z01R/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/asus/Z01R/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/asus/Z01R/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/asus/Z01R/proprietary/framework/uimremotesimlocklibrary.jar:system/framework/uimremotesimlocklibrary.jar \
    vendor/asus/Z01R/proprietary/framework/uimservicelibrary.jar:system/framework/uimservicelibrary.jar \
    vendor/asus/Z01R/proprietary/framework/vendor.qti.hardware.data.latency-V1.0-java.jar:system/framework/vendor.qti.hardware.data.latency-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/vendor.qti.ims.callinfo-V1.0-java.jar:system/framework/vendor.qti.ims.callinfo-V1.0-java.jar \
    vendor/asus/Z01R/proprietary/framework/vendor.qti.latency-V2.0-java.jar:system/framework/vendor.qti.latency-V2.0-java.jar \
    vendor/asus/Z01R/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/Z01R/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/Z01R/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/asus/Z01R/proprietary/lib/com.quicinc.cne.server@1.0.so:system/lib/com.quicinc.cne.server@1.0.so \
    vendor/asus/Z01R/proprietary/lib/extractors/libmmparser.so:system/lib/extractors/libmmparser.so \
    vendor/asus/Z01R/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/asus/Z01R/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/asus/Z01R/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/asus/Z01R/proprietary/lib/libdisplayconfig.so:system/lib/libdisplayconfig.so \
    vendor/asus/Z01R/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/asus/Z01R/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/asus/Z01R/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/asus/Z01R/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/asus/Z01R/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/asus/Z01R/proprietary/lib/liblocationservice_jni.so:system/lib/liblocationservice_jni.so \
    vendor/asus/Z01R/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/asus/Z01R/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/asus/Z01R/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/asus/Z01R/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/asus/Z01R/proprietary/lib/libqdMetaData.system.so:system/lib/libqdMetaData.system.so \
    vendor/asus/Z01R/proprietary/lib/libwfdaac.so:system/lib/libwfdaac.so \
    vendor/asus/Z01R/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/asus/Z01R/proprietary/lib/libwfdclient.so:system/lib/libwfdclient.so \
    vendor/asus/Z01R/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/asus/Z01R/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/asus/Z01R/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/asus/Z01R/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/asus/Z01R/proprietary/lib/libwfdmmservice.so:system/lib/libwfdmmservice.so \
    vendor/asus/Z01R/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/asus/Z01R/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/asus/Z01R/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/asus/Z01R/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/asus/Z01R/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/asus/Z01R/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/asus/Z01R/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/asus/Z01R/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/asus/Z01R/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/asus/Z01R/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/asus/Z01R/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/asus/Z01R/proprietary/lib/libxt_native.so:system/lib/libxt_native.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.gnss@1.1.so:system/lib/vendor.qti.gnss@1.1.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.gnss@1.2.so:system/lib/vendor.qti.gnss@1.2.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.gnss@2.0.so:system/lib/vendor.qti.gnss@2.0.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.gnss@2.1.so:system/lib/vendor.qti.gnss@2.1.so \
    vendor/asus/Z01R/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/lib64/com.quicinc.cne.server@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/extractors/libmmparser.so:system/lib64/extractors/libmmparser.so \
    vendor/asus/Z01R/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/asus/Z01R/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/asus/Z01R/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/asus/Z01R/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/asus/Z01R/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/asus/Z01R/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/asus/Z01R/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/asus/Z01R/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/asus/Z01R/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/asus/Z01R/proprietary/lib64/libdisplayconfig.so:system/lib64/libdisplayconfig.so \
    vendor/asus/Z01R/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/asus/Z01R/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/asus/Z01R/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/asus/Z01R/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/asus/Z01R/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/asus/Z01R/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/asus/Z01R/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/asus/Z01R/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/asus/Z01R/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/asus/Z01R/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/asus/Z01R/proprietary/lib64/libqdMetaData.system.so:system/lib64/libqdMetaData.system.so \
    vendor/asus/Z01R/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/asus/Z01R/proprietary/lib64/libwfdclient.so:system/lib64/libwfdclient.so \
    vendor/asus/Z01R/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/asus/Z01R/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.gnss@1.1.so:system/lib64/vendor.qti.gnss@1.1.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.gnss@1.2.so:system/lib64/vendor.qti.gnss@1.2.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.gnss@2.0.so:system/lib64/vendor.qti.gnss@2.0.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.gnss@2.1.so:system/lib64/vendor.qti.gnss@2.1.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/Z01R/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    libantradio \
    vendor.qti.hardware.fm@1.0 \
    QtiTelephonyService \
    datastatusnotification \
    embms \
    remotesimlockservice \
    uimlpaservice \
    CNEService \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentTGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    WfdService \
    com.qualcomm.location \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    xtra_t_app \
    WfdCommon \
    com.qti.location.sdk \
    izat.xt.srv
