# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/zenfone6/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/zenfone6/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/asus/zenfone6/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/asus/zenfone6/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/asus/zenfone6/proprietary/etc/nqnfcee_access.xml:system/etc/nqnfcee_access.xml \
    vendor/asus/zenfone6/proprietary/etc/nqnfcse_access.xml:system/etc/nqnfcse_access.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.gsma.services.nfc.xml:system/etc/permissions/com.gsma.services.nfc.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.nxp.nfc.nq.xml:system/etc/permissions/com.nxp.nfc.nq.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/privapp-permissions-ASUS_I01WD.xml:system/etc/permissions/privapp-permissions-ASUS_I01WD.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/asus/zenfone6/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/asus/zenfone6/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/asus/zenfone6/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/asus/zenfone6/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/asus/zenfone6/proprietary/framework/com.quicinc.cne.server-V2.3-java.jar:system/framework/com.quicinc.cne.server-V2.3-java.jar \
    vendor/asus/zenfone6/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/asus/zenfone6/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/asus/zenfone6/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/asus/zenfone6/proprietary/framework/vendor.qti.hardware.data.latency-V1.0-java.jar:system/framework/vendor.qti.hardware.data.latency-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/lib/DataSet/ispDB/ASUS_UNDI.bin:system/lib/DataSet/ispDB/ASUS_UNDI.bin \
    vendor/asus/zenfone6/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/com.quicinc.cne.server@1.0.so:system/lib/com.quicinc.cne.server@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/com.quicinc.cne.server@2.3.so:system/lib/com.quicinc.cne.server@2.3.so \
    vendor/asus/zenfone6/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/asus/zenfone6/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/asus/zenfone6/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/asus/zenfone6/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/asus/zenfone6/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/asus/zenfone6/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/asus/zenfone6/proprietary/lib/libnqnfc-nci.so:system/lib/libnqnfc-nci.so \
    vendor/asus/zenfone6/proprietary/lib/libsd_sdk_display.so:system/lib/libsd_sdk_display.so \
    vendor/asus/zenfone6/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.display.color@1.1.so:system/lib/vendor.display.color@1.1.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.display.color@1.2.so:system/lib/vendor.display.color@1.2.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.nxp.hardware.nfc@1.0.so:system/lib/vendor.nxp.hardware.nfc@1.0.so \
    vendor/asus/zenfone6/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/lib64/com.quicinc.cne.server@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/com.quicinc.cne.server@2.3.so:system/lib64/com.quicinc.cne.server@2.3.so \
    vendor/asus/zenfone6/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/asus/zenfone6/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/asus/zenfone6/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/asus/zenfone6/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/asus/zenfone6/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/asus/zenfone6/proprietary/lib64/libAsusMotorDriverHAL.so:system/lib64/libAsusMotorDriverHAL.so \
    vendor/asus/zenfone6/proprietary/lib64/libAsusRGBSensorHAL.so:system/lib64/libAsusRGBSensorHAL.so \
    vendor/asus/zenfone6/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/asus/zenfone6/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/asus/zenfone6/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/asus/zenfone6/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/asus/zenfone6/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/asus/zenfone6/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/asus/zenfone6/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/asus/zenfone6/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/asus/zenfone6/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/asus/zenfone6/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/asus/zenfone6/proprietary/lib64/libnqnfc-nci.so:system/lib64/libnqnfc-nci.so \
    vendor/asus/zenfone6/proprietary/lib64/libnqnfc_nci_jni.so:system/lib64/libnqnfc_nci_jni.so \
    vendor/asus/zenfone6/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/asus/zenfone6/proprietary/lib64/libsd_sdk_display.so:system/lib64/libsd_sdk_display.so \
    vendor/asus/zenfone6/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.display.color@1.1.so:system/lib64/vendor.display.color@1.1.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.display.color@1.2.so:system/lib64/vendor.display.color@1.2.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.display.postproc@1.0.so:system/lib64/vendor.display.postproc@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.nxp.hardware.nfc@1.0.so:system/lib64/vendor.nxp.hardware.nfc@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/zenfone6/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libUndistort.so:system/priv-app/AsusCamera/lib/arm64/libUndistort.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_undistort.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_undistort.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libasusundistort.so:system/priv-app/AsusCamera/lib/arm64/libasusundistort.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libbitmap.so:system/priv-app/AsusCamera/lib/arm64/libbitmap.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libmpbase.so:system/priv-app/AsusCamera/lib/arm64/libmpbase.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so:system/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so \
    vendor/asus/zenfone6/proprietary/priv-app/AsusCamera/lib/arm64/libyuv_util.so:system/priv-app/AsusCamera/lib/arm64/libyuv_util.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so:system/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so:system/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libjni_laser.so:system/priv-app/MotorService/lib/arm64/libjni_laser.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libjni_motor.so:system/priv-app/MotorService/lib/arm64/libjni_motor.so

PRODUCT_PACKAGES += \
    libantradio \
    vendor.qti.hardware.fm@1.0 \
    NQNfcNci \
    QtiTelephonyService \
    aptxals \
    AsusCamera \
    CNEService \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    MotorService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    com.gsma.services.nfc \
    com.nxp.nfc.nq

ifeq ($(QCPATH),)
endif

-include vendor/extra/devices.mk
ifneq ($(call is-qc-perf-target),true)
endif
