# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/zenfone6/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/zenfone6/proprietary/etc/cne/Nexus/ATT/ATT_profiles.xml:system/etc/cne/Nexus/ATT/ATT_profiles.xml \
    vendor/asus/zenfone6/proprietary/etc/cne/Nexus/ROW/ROW_profiles.xml:system/etc/cne/Nexus/ROW/ROW_profiles.xml \
    vendor/asus/zenfone6/proprietary/etc/cne/Nexus/VZW/VZW_profiles.xml:system/etc/cne/Nexus/VZW/VZW_profiles.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/asus/zenfone6/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/asus/zenfone6/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/asus/zenfone6/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/asus/zenfone6/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/asus/zenfone6/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/asus/zenfone6/proprietary/lib/DataSet/ispDB/ASUS_UNDI.bin:system/lib/DataSet/ispDB/ASUS_UNDI.bin \
    vendor/asus/zenfone6/proprietary/lib/DataSet/ispDB/ASUS_UNDI_ZOOM.bin:system/lib/DataSet/ispDB/ASUS_UNDI_ZOOM.bin \
    vendor/asus/zenfone6/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/asus/zenfone6/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/asus/zenfone6/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/asus/zenfone6/proprietary/lib64/libAsusRGBSensorHAL.so:system/lib64/libAsusRGBSensorHAL.so \
    vendor/asus/zenfone6/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/asus/zenfone6/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/asus/zenfone6/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/asus/zenfone6/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/asus/zenfone6/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/asus/zenfone6/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so:system/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so:system/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libjni_laser.so:system/priv-app/MotorService/lib/arm64/libjni_laser.so \
    vendor/asus/zenfone6/proprietary/priv-app/MotorService/lib/arm64/libjni_motor.so:system/priv-app/MotorService/lib/arm64/libjni_motor.so \
    vendor/asus/zenfone6/proprietary/product/bin/dpmd:system/product/bin/dpmd \
    vendor/asus/zenfone6/proprietary/product/etc/dpm/dpm.conf:system/product/etc/dpm/dpm.conf \
    vendor/asus/zenfone6/proprietary/product/etc/init/dpmd.rc:system/product/etc/init/dpmd.rc \
    vendor/asus/zenfone6/proprietary/product/etc/permissions/com.qti.dpmframework.xml:system/product/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/zenfone6/proprietary/product/etc/permissions/dpmapi.xml:system/product/etc/permissions/dpmapi.xml \
    vendor/asus/zenfone6/proprietary/product/etc/permissions/qcrilhook.xml:system/product/etc/permissions/qcrilhook.xml \
    vendor/asus/zenfone6/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:system/product/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/asus/zenfone6/proprietary/product/etc/permissions/telephonyservice.xml:system/product/etc/permissions/telephonyservice.xml \
    vendor/asus/zenfone6/proprietary/product/framework/QtiTelephonyServicelibrary.jar:system/product/framework/QtiTelephonyServicelibrary.jar \
    vendor/asus/zenfone6/proprietary/product/framework/com.qti.dpmframework.jar:system/product/framework/com.qti.dpmframework.jar \
    vendor/asus/zenfone6/proprietary/product/framework/com.quicinc.cne.api-V1.1-java.jar:system/product/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/com.quicinc.cne.constants-V1.0-java.jar:system/product/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/com.quicinc.cne.constants-V2.0-java.jar:system/product/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/com.quicinc.cne.constants-V2.1-java.jar:system/product/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/dpmapi.jar:system/product/framework/dpmapi.jar \
    vendor/asus/zenfone6/proprietary/product/framework/qcrilhook.jar:system/product/framework/qcrilhook.jar \
    vendor/asus/zenfone6/proprietary/product/framework/vendor.qti.hardware.data.cne.internal.api-V1.0-java.jar:system/product/framework/vendor.qti.hardware.data.cne.internal.api-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/vendor.qti.hardware.data.cne.internal.constants-V1.0-java.jar:system/product/framework/vendor.qti.hardware.data.cne.internal.constants-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/product/framework/vendor.qti.hardware.data.iwlan-V1.0-java.jar:system/product/framework/vendor.qti.hardware.data.iwlan-V1.0-java.jar \
    vendor/asus/zenfone6/proprietary/product/lib/com.qualcomm.qti.ant@1.0.so:system/product/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.qualcomm.qti.dpm.api@1.0.so:system/product/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.quicinc.cne.api@1.0.so:system/product/lib/com.quicinc.cne.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.quicinc.cne.api@1.1.so:system/product/lib/com.quicinc.cne.api@1.1.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.quicinc.cne.constants@1.0.so:system/product/lib/com.quicinc.cne.constants@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.quicinc.cne.constants@2.0.so:system/product/lib/com.quicinc.cne.constants@2.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/com.quicinc.cne.constants@2.1.so:system/product/lib/com.quicinc.cne.constants@2.1.so \
    vendor/asus/zenfone6/proprietary/product/lib/libdpmctmgr.so:system/product/lib/libdpmctmgr.so \
    vendor/asus/zenfone6/proprietary/product/lib/libdpmfdmgr.so:system/product/lib/libdpmfdmgr.so \
    vendor/asus/zenfone6/proprietary/product/lib/libdpmframework.so:system/product/lib/libdpmframework.so \
    vendor/asus/zenfone6/proprietary/product/lib/libdpmtcm.so:system/product/lib/libdpmtcm.so \
    vendor/asus/zenfone6/proprietary/product/lib/libsd_sdk_display.qti.so:system/product/lib/libsd_sdk_display.qti.so \
    vendor/asus/zenfone6/proprietary/product/lib/libsdm-disp-apis.qti.so:system/product/lib/libsdm-disp-apis.qti.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.display.color@1.0.so:system/product/lib/vendor.display.color@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.display.color@1.1.so:system/product/lib/vendor.display.color@1.1.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.display.color@1.2.so:system/product/lib/vendor.display.color@1.2.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.display.color@1.3.so:system/product/lib/vendor.display.color@1.3.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.display.postproc@1.0.so:system/product/lib/vendor.display.postproc@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.qti.hardware.data.cne.internal.api@1.0.so:system/product/lib/vendor.qti.hardware.data.cne.internal.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.qti.hardware.data.cne.internal.constants@1.0.so:system/product/lib/vendor.qti.hardware.data.cne.internal.constants@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.qti.hardware.data.cne.internal.server@1.0.so:system/product/lib/vendor.qti.hardware.data.cne.internal.server@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib/vendor.qti.hardware.fm@1.0.so:system/product/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.qualcomm.qti.ant@1.0.so:system/product/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/product/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.quicinc.cne.api@1.0.so:system/product/lib64/com.quicinc.cne.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.quicinc.cne.api@1.1.so:system/product/lib64/com.quicinc.cne.api@1.1.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.quicinc.cne.constants@1.0.so:system/product/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.quicinc.cne.constants@2.0.so:system/product/lib64/com.quicinc.cne.constants@2.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/com.quicinc.cne.constants@2.1.so:system/product/lib64/com.quicinc.cne.constants@2.1.so \
    vendor/asus/zenfone6/proprietary/product/lib64/lib-imsvideocodec.so:system/product/lib64/lib-imsvideocodec.so \
    vendor/asus/zenfone6/proprietary/product/lib64/lib-imsvt.so:system/product/lib64/lib-imsvt.so \
    vendor/asus/zenfone6/proprietary/product/lib64/lib-imsvtextutils.so:system/product/lib64/lib-imsvtextutils.so \
    vendor/asus/zenfone6/proprietary/product/lib64/lib-imsvtutils.so:system/product/lib64/lib-imsvtutils.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libdpmctmgr.so:system/product/lib64/libdpmctmgr.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libdpmfdmgr.so:system/product/lib64/libdpmfdmgr.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libdpmframework.so:system/product/lib64/libdpmframework.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libdpmtcm.so:system/product/lib64/libdpmtcm.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libimscamera_jni.so:system/product/lib64/libimscamera_jni.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libimsmedia_jni.so:system/product/lib64/libimsmedia_jni.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libsd_sdk_display.qti.so:system/product/lib64/libsd_sdk_display.qti.so \
    vendor/asus/zenfone6/proprietary/product/lib64/libsdm-disp-apis.qti.so:system/product/lib64/libsdm-disp-apis.qti.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.display.color@1.0.so:system/product/lib64/vendor.display.color@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.display.color@1.1.so:system/product/lib64/vendor.display.color@1.1.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.display.color@1.2.so:system/product/lib64/vendor.display.color@1.2.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.display.color@1.3.so:system/product/lib64/vendor.display.color@1.3.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.display.postproc@1.0.so:system/product/lib64/vendor.display.postproc@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@1.0.so:system/product/lib64/vendor.qti.gnss@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@1.1.so:system/product/lib64/vendor.qti.gnss@1.1.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@1.2.so:system/product/lib64/vendor.qti.gnss@1.2.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@2.0.so:system/product/lib64/vendor.qti.gnss@2.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@2.1.so:system/product/lib64/vendor.qti.gnss@2.1.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.gnss@3.0.so:system/product/lib64/vendor.qti.gnss@3.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.api@1.0.so:system/product/lib64/vendor.qti.hardware.data.cne.internal.api@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.constants@1.0.so:system/product/lib64/vendor.qti.hardware.data.cne.internal.constants@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.server@1.0.so:system/product/lib64/vendor.qti.hardware.data.cne.internal.server@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.hardware.fm@1.0.so:system/product/lib64/vendor.qti.hardware.fm@1.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.imsrtpservice@2.0.so:system/product/lib64/vendor.qti.imsrtpservice@2.0.so \
    vendor/asus/zenfone6/proprietary/product/lib64/vendor.qti.imsrtpservice@2.1.so:system/product/lib64/vendor.qti.imsrtpservice@2.1.so

PRODUCT_PACKAGES += \
    libantradio \
    aptxals \
    aptxalsOverlay \
    MotorService \
    com.qualcomm.location \
    QtiTelephonyService \
    AndroidAutoStub \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel

ifeq ($(QCPATH),)
endif

-include vendor/extra/devices.mk
ifneq ($(call is-qc-perf-target),true)
endif
