# Copyright (C) 2020-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/zenfone7/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/zenfone7

PRODUCT_COPY_FILES += \
    vendor/asus/zenfone7/proprietary/etc/permissions/asus.hardware.motor.latch_lock.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/asus.hardware.motor.latch_lock.xml \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Charming.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Charming.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Dynamic.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Dynamic.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Energetic.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Energetic.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Graceful.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Graceful.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Happy.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Happy.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Lively.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Lively.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor/Soothing.mfim:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor/Soothing.mfim \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/12BB667E-32CC-4511-BB3E-07BE054A2896.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/12BB667E-32CC-4511-BB3E-07BE054A2896.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/12FCD2E7-1F80-4DFC-A8FD-C820CF754855.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/12FCD2E7-1F80-4DFC-A8FD-C820CF754855.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/2215EC1E-A9EE-4B5C-89CB-BF488178C910.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/2215EC1E-A9EE-4B5C-89CB-BF488178C910.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/27C20D68-D75E-42F0-BD1A-0927D5B3A20C.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/27C20D68-D75E-42F0-BD1A-0927D5B3A20C.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/394EB525-1B7A-4AA1-BBAD-3FD75527A60C.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/394EB525-1B7A-4AA1-BBAD-3FD75527A60C.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/52AEDFE9-E76E-4AE5-91C5-6C6466F335E2.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/52AEDFE9-E76E-4AE5-91C5-6C6466F335E2.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/576A09D7-766B-427F-AF19-E8BD6B6F2F1B.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/576A09D7-766B-427F-AF19-E8BD6B6F2F1B.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/61B3A8B9-C843-450D-AB93-56FF082FF120.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/61B3A8B9-C843-450D-AB93-56FF082FF120.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/6439CF7E-42D5-4239-8187-358323292FF4.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/6439CF7E-42D5-4239-8187-358323292FF4.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/749C7148-F6C7-418A-B177-3493994A5F84.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/749C7148-F6C7-418A-B177-3493994A5F84.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/7D8A1839-B7D3-4C91-AD7A-8FB920322818.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/7D8A1839-B7D3-4C91-AD7A-8FB920322818.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/8615918E-FEB9-47F8-AEAA-B648E61E9314.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/8615918E-FEB9-47F8-AEAA-B648E61E9314.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/89B2D082-5F47-4A6D-9FD0-9F1BB053F6A7.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/89B2D082-5F47-4A6D-9FD0-9F1BB053F6A7.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/A8A4344D-45DA-460F-A18F-C0E2355FE864.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/A8A4344D-45DA-460F-A18F-C0E2355FE864.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/B7F1F498-B310-4E2D-9A75-7D8AFBBC71D8.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/B7F1F498-B310-4E2D-9A75-7D8AFBBC71D8.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/BCD1FAAD-D5C5-468F-A4F2-1C2138F485C0.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/BCD1FAAD-D5C5-468F-A4F2-1C2138F485C0.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/D71CB384-ECCA-48E6-B791-C15EDB326F56.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/D71CB384-ECCA-48E6-B791-C15EDB326F56.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/F17F414B-B1E2-4FB8-BD29-FEFDA43FCB98.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/F17F414B-B1E2-4FB8-BD29-FEFDA43FCB98.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/FE794398-0AA5-4A1C-8189-7A00B516CF0E.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/FE794398-0AA5-4A1C-8189-7A00B516CF0E.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/fx/FE91A908-A0C1-424D-A9FF-05386BA49316.videofx:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/fx/FE91A908-A0C1-424D-A9FF-05386BA49316.videofx \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/1.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/1.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/10.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/10.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/2.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/2.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/3.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/3.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/4.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/4.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/5.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/5.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/6.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/6.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/7.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/7.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/8.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/8.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/music/9.mp3:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/music/9.mp3 \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/0ABAAB00-D327-4650-A6C3-71252C6B752D.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/0ABAAB00-D327-4650-A6C3-71252C6B752D.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/249B5FAC-CC0B-4745-AFE2-46B875C80CDA.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/249B5FAC-CC0B-4745-AFE2-46B875C80CDA.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/3F3E7A79-3D3B-4B0B-B6B5-414C4DB6A283.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/3F3E7A79-3D3B-4B0B-B6B5-414C4DB6A283.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/4923FF1B-6459-42C9-BC81-CC641C52F0C1.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/4923FF1B-6459-42C9-BC81-CC641C52F0C1.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/BA915657-4E49-4EBA-970F-26DBF2E88D60.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/BA915657-4E49-4EBA-970F-26DBF2E88D60.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/D1DC85A4-3C8F-49D8-8EB4-6E30852EEC19.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/D1DC85A4-3C8F-49D8-8EB4-6E30852EEC19.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/D363C1F8-2D14-4D88-AB9D-1E8AEEF3AEFE.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/D363C1F8-2D14-4D88-AB9D-1E8AEEF3AEFE.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/F2969925-7BA9-4C6D-A91C-6DE327EB9B30.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/F2969925-7BA9-4C6D-A91C-6DE327EB9B30.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/F91F37A8-BD10-40B5-A476-56019566D015.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/F91F37A8-BD10-40B5-A476-56019566D015.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/theme/FBDF22EE-8908-4736-BEA9-BC10D3C0574D.theme:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/theme/FBDF22EE-8908-4736-BEA9-BC10D3C0574D.theme \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/0499C962-9CDE-4B0C-A4DC-3F09C5A8D12E.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/0499C962-9CDE-4B0C-A4DC-3F09C5A8D12E.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/0F241EB7-BD8C-491F-BC46-8776FEDA4C97.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/0F241EB7-BD8C-491F-BC46-8776FEDA4C97.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/3DEFF9D6-C2A4-4A1E-A817-BA90565D1AD4.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/3DEFF9D6-C2A4-4A1E-A817-BA90565D1AD4.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/54C93F85-C026-4EBE-80CD-F51C31D5E07D.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/54C93F85-C026-4EBE-80CD-F51C31D5E07D.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/641DC0DC-FDF9-4DF7-A268-C5F5B0E3293E.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/641DC0DC-FDF9-4DF7-A268-C5F5B0E3293E.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/71EB679A-4B0F-4218-8F38-1B4BCBD48266.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/71EB679A-4B0F-4218-8F38-1B4BCBD48266.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/8DD3F560-A587-4C09-9AEC-9DA38AA5D5C5.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/8DD3F560-A587-4C09-9AEC-9DA38AA5D5C5.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/9CA48E0E-9523-4408-BEEA-DCCF7B5A4024.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/9CA48E0E-9523-4408-BEEA-DCCF7B5A4024.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/D691C32F-D9E5-40B2-9718-C15224D6E121.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/D691C32F-D9E5-40B2-9718-C15224D6E121.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/EB2B0E57-C3BF-4361-802A-90620C5CCEDE.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/EB2B0E57-C3BF-4361-802A-90620C5CCEDE.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/ECE4B448-D61B-49CB-BD17-580582703061.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/ECE4B448-D61B-49CB-BD17-580582703061.videotransition \
    vendor/asus/zenfone7/proprietary/etc/videoeditor7/transition/FCC6384D-1459-4C44-B05F-496AFC472A83.videotransition:$(TARGET_COPY_OUT_SYSTEM)/etc/videoeditor7/transition/FCC6384D-1459-4C44-B05F-496AFC472A83.videotransition \
    vendor/asus/zenfone7/proprietary/lib64/DataSet/arch/DIT_List.cfg:$(TARGET_COPY_OUT_SYSTEM)/lib64/DataSet/arch/DIT_List.cfg \
    vendor/asus/zenfone7/proprietary/lib64/DataSet/ditSCidGen/msgchk.db:$(TARGET_COPY_OUT_SYSTEM)/lib64/DataSet/ditSCidGen/msgchk.db \
    vendor/asus/zenfone7/proprietary/lib64/DataSet/ispDB/ParameterDB.db:$(TARGET_COPY_OUT_SYSTEM)/lib64/DataSet/ispDB/ParameterDB.db \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_DIT_MSMv1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_DIT_MSMv1.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_DIT_Manager.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_DIT_Manager.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_ISP.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_ISP.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_arch.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_arch.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_ditArchLIB.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_ditArchLIB.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_ditBSP.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_ditBSP.so \
    vendor/asus/zenfone7/proprietary/lib64/libxditk_ditBSP_JNI.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxditk_ditBSP_JNI.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libUndistort.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libUndistort.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_interval_capture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_interval_capture.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_portrait_distortion_correction_rog3.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libarcsoft_portrait_distortion_correction_rog3.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_portrait_distortion_correction_zf7.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libarcsoft_portrait_distortion_correction_zf7.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_interval_panorama.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libasus_camera_interval_panorama.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libasusundistort.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libasusundistort.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libbitmap.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libbitmap.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libmpbase.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libyuv_camera.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libyuv_camera.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusCamera/lib/arm64/libyuv_util.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusCamera/lib/arm64/libyuv_util.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libNvStreamingSdkCore.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libNvStreamingSdkCore.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libRSSupport.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libRSSupport.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libarcsoft_beautyshot.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libarcsoft_undistort.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libarcsoft_undistort.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libblur.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libblur.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libcvface_api.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libcvface_api.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libgif.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libgif.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libgvr.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libgvr.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libjni_cvface_api.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libjni_cvface_api.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libjni_face_effect.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libjni_face_effect.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libjni_filter_show.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libjni_filter_show.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libjni_wide_angle_undistort.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libjni_wide_angle_undistort.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libmpbase.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libopencv_java3.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libopencv_java3.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libpano_video_renderer.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libpano_video_renderer.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libpanorenderer.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libpanorenderer.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.blur.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.blur.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.convolve3x3.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.convolve3x3.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.grad.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.grad.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.grey.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.grey.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.saturation.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.saturation.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librs.vignette.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librs.vignette.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librsjni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librsjni.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/librsjni_androidx.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/librsjni_androidx.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libtensorflow_inference.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libtensorflow_inference.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGallery/lib/arm64/libtensorflowlite_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGallery/lib/arm64/libtensorflowlite_jni.so \
    vendor/asus/zenfone7/proprietary/priv-app/AsusGalleryBurst/lib/arm/libgifencoder.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/AsusGalleryBurst/lib/arm/libgifencoder.so \
    vendor/asus/zenfone7/proprietary/priv-app/MotorK/lib/arm64/libAsusMotorDriverHAL.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MotorK/lib/arm64/libAsusMotorDriverHAL.so \
    vendor/asus/zenfone7/proprietary/priv-app/MotorK/lib/arm64/libmotork-jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MotorK/lib/arm64/libmotork-jni.so \
    vendor/asus/zenfone7/proprietary/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so \
    vendor/asus/zenfone7/proprietary/priv-app/MotorService/lib/arm64/libjni_motor.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MotorService/lib/arm64/libjni_motor.so \
    vendor/asus/zenfone7/proprietary/product/etc/permissions/com.qti.snapdragon.sdk.display.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/libsd_sdk_display.qti.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libsd_sdk_display.qti.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/libsdm-disp-apis.qti.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libsdm-disp-apis.qti.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.display.color@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.display.color@1.0.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.display.color@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.display.color@1.1.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.display.color@1.2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.display.color@1.2.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.display.color@1.3.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.display.color@1.3.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.display.postproc@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.display.postproc@1.0.so \
    vendor/asus/zenfone7/proprietary/system_ext/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.hardware.qdutils_disp@1.0.so

PRODUCT_PACKAGES += \
    AsusCamera \
    AsusGallery \
    AsusGalleryBurst \
    MotorK \
    MotorService \
    colorservice \
    QPerformance \
    UxPerformance \
    com.qti.snapdragon.sdk.display
